version: '3.9'

services:
  # Zookeeper
  zookeeper:
    image: 'quay.io/debezium/zookeeper:2.6'
    ports: 
      - '2181:2181'
      - '2888:2888'
      - '3888:3888'
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    tty: true
    networks:
      - kafka_network

  # Kafka Broker
  kafka:
    image: 'quay.io/debezium/kafka:2.6'
    ports:
      - '9092:9092'
      - '9093:9093'
      - '9094:9094'
    container_name: kafka
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper
    tty: true
    networks:
      - kafka_network

  # Kafka UI
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - '8081:8081'
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=2181
      - KAFKA_CLUSTERS_0_READONLY=false
      - SERVER_PORT=8081
    networks:
      - kafka_network

  mysql:
    image: "mysql:8.0.32"
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_USER=mysqluser"
      - "MYSQL_PASSWORD=mysqlpw"
    networks:
      - "kafka_network"

  connect:
    image: "quay.io/debezium/connect:2.6"
    container_name: connect
    depends_on:
      - "zookeeper"
      - "kafka"
      - "mysql"
    ports:
      - "8083:8083"
    environment:
      - "BOOTSTRAP_SERVERS=kafka:9092"
      - "GROUP_ID=1"
      - "CONFIG_STORAGE_TOPIC=test2"
      - "OFFSET_STORAGE_TOPIC=test3"
      - "STATUS_STORAGE_TOPIC=test4"
    networks:
      - kafka_network

  debezium-ui:
    image: "quay.io/debezium/debezium-ui:2.4"
    container_name: debezium-ui
    depends_on:
      - "connect"
    ports:
      - "8080:8080"
    environment:
      - "KAFKA_CONNECT_URIS=http://connect:8083"
    networks:
      - kafka_network
networks:
  kafka_network:
